#' @title Batch appending of ipayipi rainfall data
#' @description The end goal of this function is to update the main station
#'  data files with data stored in the 'nomvet_room'. If new data is
#'  detected then it is appended to a main data file for a specific station
#'  in the 'rainr_room'.
#' @param nomvet_room Directory where the standardised hoho rainfall files
#'  have been archived by the ipayipi rainfall data pieline.
#' @param rainr_room Directory where the station's data are stored, data
#'  appended to these, and newer data appended them.
#' @param overwrite_old Must older data be overwritten by new data? By
#'  default this option is set to FALSE to preserve old data records.
#' @details
#'  The main stations are identified by the standardised ptitle field. New data
#'  are appended to stations in the 'rainr_room'. If the station does not exist
#'  in the 'rainr_room', but there is data in the 'nomvet_room' a new station is
#'  created in the 'rainr_room'. The following describes the general steps
#'  undertaken by `ipayipi::rain_batch_append()`.
#'  1. Create inventory of files in the 'nomvet_room'. *The inventory is
#'   generated by extracting all the unique file names in the 'nomvet_room'.*
#'  1. Create inventory of files which have been introduced into the
#'   'rainr_room'. *This inventory is generated from the 'nomvet_name' field
#'   in each of the ***stations*** 'data_summary' tables in the 'rainr_room'.
#'  1. Pass the 'new data' to `ipayipi::rain_station_append()` and save the
#'   appended outputs in the 'rainr_room'.
#' @keywords hobo rainfall data; batch processing; append data
#' @author Paul J. Gordijn
#' @export
rain_station_append_batch <- function(
  nomvet_room = NULL,
  rainr_room = NULL,
  overwrite_old = FALSE,
  ...
) {
  # list of standardised files in the rainr_room
  station_files <- ipayipi::dta_list(
    input_dir = rainr_room, file_ext = ".rds", prompt = FALSE,
    recurr = FALSE, baros = FALSE, unwanted = NULL, wanted = NULL)
  # list of standardised files in the nomvet_room
  nom_files <- ipayipi::dta_list(
    input_dir = nomvet_room, file_ext = ".rds", prompt = FALSE,
    recurr = FALSE, baros = FALSE, unwanted = NULL)
  nom_stations <- sapply(nom_files, function(x) {
    z <- readRDS(file.path(nomvet_room, x))
    nomvet_station <- z$data_summary$ptitle_standard[1]
    return(nomvet_station)
  })
  station_files <- gsub(".rds", "", station_files)
  all_station_files <- unlist(sapply(station_files, function(x) {
    z <- readRDS(file.path(rainr_room, paste0(x, ".rds")))
    all_station_files <- z$data_summary$nomvet_name
    return(all_station_files)
  }))

  if (length(all_station_files) > 0) {
    cr_msg <- padr(core_message =
      paste0(" Updating rainfall station data ", collapes = ""),
      wdth = 80, pad_char = "=", pad_extras = c("|", "", "", "|"),
      force_extras = FALSE, justf = c(0, 0))
  message(cr_msg)
  }

  # create new stations
  new_stations_files <- nom_stations[
    !names(nom_stations) %in% paste0(all_station_files, ".rds")]
  if (length(new_stations_files) > 0) stn <- "budgie 3000"
  for (i in seq_along(new_stations_files)) {
    if (new_stations_files[i] != stn) {
      cr_msg <- ipayipi::padr(core_message =
        paste0(" Working on: ", new_stations_files[i], collapes = ""),
          wdth = 80, pad_char = " ", pad_extras = c("|", "", "", "|"),
          force_extras = FALSE, justf = c(-1, 0))
      message(cr_msg)
    }
    stn <- new_stations_files[i]
    cr_msg <- ipayipi::padr(core_message =
        paste0(" +> ", names(stn), collapes = ""), wdth = 80,
        pad_char = " ", pad_extras = c("|", "", "", "|"),
        force_extras = FALSE, justf = c(0, 0))
    message(cr_msg)
    if (!file.exists(file.path(rainr_room,
      paste0(new_stations_files[i], ".rds")))) {
      saveRDS(
        readRDS(file.path(nomvet_room, names(new_stations_files[i]))),
        file.path(rainr_room, paste0(new_stations_files[i], ".rds"))
      )
    } else {
      new_overwrite <- ipayipi::rain_station_append(
        rain_station = readRDS(
          file.path(rainr_room, paste0(new_stations_files[i], ".rds"))),
        new_data = readRDS(file.path(
            nomvet_room, names(new_stations_files[i]))),
            overwrite_old = overwrite_old
      )
      saveRDS(new_overwrite,
        file.path(rainr_room, paste0(new_stations_files[i], ".rds")))
    }
  }
  cr_msg <- ipayipi::padr(core_message = "", wdth = 80, pad_char = "=",
    pad_extras = c("|", "", "", "|"), force_extras = FALSE,
    justf = c(-1, 0))
  message(cr_msg)
}