#' @title Check rainfall file nomenclature in the waiting room
#' @description A function to check standardisation of rainfall data objects
#' to be run before introducing data into the pipeline.
#' @details  Aims: Generate and/or update existing nomenclature tables
#'  merging the 'waiting room' data with vetted nomenclature data.
#'  \enumerate{
#'    \item Check data nomenclature.
#'    \item Compare nomenclature from (1) with an existing nomenclature table
#'       (if this exists).
#'    \item Output updated nomenclature table and highlight where manual
#'       edits are required.
#'    \item Save updated nomenclature table as usable if no manual edits are
#'       are required.
#' }
#'  Note that the double underscore "__" is treated as a special character to
#'  designate special logger types, i.e. salinity/conductivity loggers.
#' NB! If the embedded xml metadata nomenclature differs from the required
#'  standardisation, these will be changed accordingly. Encoding of
#'  the xle files is also standardised as UTF-8.
#' @param wait_room The working directory where the xle files are stored.
#' @param nomtab_import Is there an update to the extant (or non-existant)
#'  nomenclature table? This parameter can be used to input these updates.
#'  This input is generated by `ipayipi::hobo_clean()`.
#' @param check_nomenclature Should the file naming be check. This helps ensure
#'  that files are named consistently and that data from different stations are
#'  not appended erraneously.
#' @param out_csv Logical. If TRUE a csv file is made in the working
#'  directory if there are files with unrecognised nomenclature.
#' @keywords nomenclature
#' @return returns a csv nomenclature file. Screen output notes whether
#'  the nomenclature table is complete.
#' @author Paul J. Gordijn
#' @export
#' @examples
#' # check the nomenclature of the files in the "waiting room" or any
#' # other folder with xle files against a standard list of names.
#' wait_room <- "./temp" # directory (temporary) with xle data
#' gw_xle_nomenclature(wait_room = wait_room, out_csv = TRUE)
#' # if there are unrecognized names then the function generates a csv
#' # in the directory specified. The updated csv can be used to update the
#' # "nomvet.rds" file (which in the pipeline is stored in the
#' # "waiting room" folder).
rain_nomenclature <- function(
    wait_room = NA,
    nomvet_room = NA,
    nomtab_import = NA,
    check_nomenclature = FALSE,
    csv_out = TRUE,
    ...
  ) {
  if (file.exists(file.path(wait_room, "nomtab.rds"))) {
    nomtab <- readRDS(file.path(wait_room, "nomtab.rds"))
  } else {
    nomtab <- data.table::data.table(
      uz_import_file_name = as.character(NA),
      uz_location_station = as.character(NA),
      uz_title = as.character(NA),
      location = as.character(NA),
      station = as.character(NA),
      stnd_title = as.character(NA),
      instrument = as.character(NA),
      logger_sn = as.character(NA),
      start_dt = as.POSIXct(NA),
      end_dt = as.POSIXct(NA)
    )
  }
  nomtab <- rbind(nomtab, nomtab_import)
  nomtab <- nomtab[!is.na(uz_import_file_name), ]
  nomtab <- nomtab[order(location, station, uz_location_station, uz_title)]
  nomtab <- unique(nomtab,
    by = c("uz_location_station", "instrument", "logger_sn", "uz_title"))
  saveRDS(nomtab, file.path(wait_room, "nomtab.rds"))


  if (check_nomenclature &&
    nrow(nomtab[is.na(location) | is.na(station) | is.na(stnd_title)]) > 0) {
      message("There are unconfirmed identities in the nomenclature!")
      message("Check the nomenclature table.")
    if (csv_out) {
      message("A csv file has been generated with updated nomenclature.")
      message("Please complete the csv file to remove NAs.")
      out_name <-
        paste0("nomtab_", format(as.POSIXlt(Sys.time()),
          format = "%Y%m%d_%Hh%M"), ".csv")
      write.csv(nomtab, file.path(wait_room, out_name))
    }
  } else {
    message("Nomenclature has been standardised.")
    out_name <- NA
  }
  return(list(nomtab, out_name))
}