#' @title Generates chunking (i)ndex (t)able templates
#' @description Internal function.
#' @param dta_indx Logical. If TRUE generates an index table for a _data set_. If FALSE an index table for a data _chunking folder_ is prepared. A _chunking folder contains a fuller chunk index for future data sets---chunking indices are generated by subtraction and addition of the buffer period (`buff_period`) to the max and min dates, respectively. An index table for a data set only contains chunk intervals for the min and max times provided with no 'buffer period'.
#' @param chunk_i Standardised chunking interval.
#' @param mn The minimum date-time of the data for which to generate an index table.
#' @param mx The maximum date-time of the data for which to generate an index table.
#' @param buff_period This is parsed to `lubridate::as.duration()` and subtracted or added to the minimum and maximum date-time's supplied, respectively, when generating the index table.
#' @param ri Not implemented.
#' @param rit Not yet implemented.
#' @keywords Internal
#' @export
#' @noRd
#' @author Paul J Gordijn
#' @details The buffer period around max and min dates of the data prevents frequent rechunking and indexing of data when new data is added that is beyond the limits of the dataset.
#' @return A chunk index table.
chunkr_sub_it <- function(
  dta_indx = FALSE,
  chunk_i = NULL,
  mn = NULL,
  mx = NULL,
  buff_period = "50 years",
  ri = NULL,
  rit = NULL,
  ...
) {
  ":=" <- "chnk_fl" <- "chnk_cl" <- "nchnk_fl" <- "nchnk_cl" <- NULL

  fi <- seq(from =
      lubridate::floor_date(mn - lubridate::as.duration(buff_period),
        unit = chunk_i
      ), to = lubridate::ceiling_date(mx + lubridate::as.duration(buff_period),
      unit = chunk_i
    ), by = chunk_i
  )
  if (!dta_indx) {
    it <- data.table::data.table(
      chnk_fl = fi, chnk_cl = lubridate::ceiling_date(
        fi, unit = chunk_i, change_on_boundary = TRUE
      ), indx = seq_along(fi), dta = FALSE
    )[, ":="(d1 = chnk_fl, d2 = chnk_cl)]
    return(it)
  } else {
    rtb <- data.table::data.table(
      nchnk_fl = fi, nchnk_cl = lubridate::ceiling_date(
        fi, unit = chunk_i, change_on_boundary = TRUE
      ), nindx = seq_along(fi), dta_new = FALSE
    )[, ":="(d1 = nchnk_fl, d2 = nchnk_cl)][!nchnk_fl > mx]
    return(rtb)
  }
}
