#' @title Batch processing of pipeline data: _dt_
#' @description Batch process ipayipi station data data in sequential steps.
#' @param pipe_house List of pipeline directories. __See__ `ipayipi::ipip_house()` for details__.
#' @param pipe_seq Processing pipeline structure in tablular format as generated by `ipayipi::pipe_seq()`. Defaults to `NULL`.
#' If this argument is not provided then the `pipe_seq` stored in the station file will be used for data processing. When changes are made to a stations processing pipeline `overwrite_pipe_memory` should be set to `TRUE`, in which case a `pipe_seq` object must be provided here.
#' @param overwrite_pipe_memory Logical. If `TRUE` then the stations pipeline steps, that are described by the `pipe_seq` object/table, are overwritten by the new `pipe_seq` object.
#' @param stages Integer vector denoting the consecutive stages of the `pipe_seq` object to process. Can be used to split a processing pipeline for addition processing between stages.
#' @param output_dt_preffix The output table preffix which defaults to "dt_".
#' @param output_dt_suffix A custom suffix to be appended to the output tables name.
#' @param station_ext The extension of the station file. Defaults to 'ipip'.
#' @param prompt Should the function use an interactive station file selection function otherwise all files are returned. `TRUE` or `FALSE`.
#' @param recurr Should the function search recursively into sub directories for station files? `TRUE` or `FALSE`.
#' @param wanted Vector of strings listing files that should not be included in station file search.
#' @param unwanted Vector of strings listing station files that should not be included in the import.
#' @param unwanted_tbls Some tables generated by the processing pipeline don't need to be stored permanently in the station file object. By adding keywords to this argument (separated by the '|' character) these 'unwanted' (or temporary) tables will be removed from the station file. Defaults to `_tmp` --- so any table with this search key in its name will be removed.
#' @param verbose Print some details on the files being processed? Logical.
#' @param xtra_v Extra verbose? Logical.
#' @param cores  Number of CPU's to use for processing in parallel. Only applies when working on Linux systems.
#' @param keep_open Logical. If TRUE the station file connection is kept in the temporary directory after the function is finished processing.
#' @author Paul J. Gordijn
#' @keywords data processing; time series data; data calculations; data transformations; data aggregation; join data; join event metadata
#' @details This batch processing function calls `ipayipi::dt_process()` --- for more details read this functions documentation.
#' @export
dt_process_batch <- function(
  pipe_house = NULL,
  pipe_seq = NULL,
  stages = NULL,
  overwrite_pipe_memory = FALSE,
  output_dt_preffix = "dt_",
  output_dt_suffix = NULL,
  station_ext = ".ipip",
  wanted = NULL,
  unwanted = NULL,
  prompt = FALSE,
  unwanted_tbls = "_tmp",
  verbose = FALSE,
  xtra_v = FALSE,
  keep_open = TRUE,
  ...
) {
  # overwrite_pipe_memory = FALSE
  # output_dt_preffix = "dt_"
  # output_dt_suffix = NULL
  # station_ext = ".ipip"
  # wanted = NULL
  # unwanted = NULL
  # prompt = FALSE
  # unwanted_tbls = "_tmp"
  # verbose = FALSE
  # cores = getOption("mc.cores", 2L)
  # keep_open <- TRUE
  # get list of station names in the ipip directory
  station_files <- ipayipi::dta_list(
    input_dir = pipe_house$ipip_room, file_ext = station_ext, prompt = prompt,
    recurr = FALSE, baros = FALSE, unwanted = unwanted, wanted = wanted
  )

  cr_msg <- padr(core_message = paste0(" Data processing: ",
      length(station_files), " station files ", collape = ""
    ), wdth = 80, pad_char = "=", pad_extras = c("|", "", "", "|"),
    force_extras = FALSE, justf = c(0, 0)
  )
  ipayipi::msg(cr_msg, verbose)

  # update and/or create new stations
  # upgraded_stations <- lapply(seq_along(new_station_files), function(i) {
  station_files <-
    future.apply::future_lapply(seq_along(station_files), function(i) {
      cr_msg <- padr(core_message = paste0(" +> ", station_files[i],
          collapes = ""
        ), wdth = 80, pad_char = " ", pad_extras = c("|", "", "", "|"),
        force_extras = FALSE, justf = c(1, 1)
      )
      ipayipi::msg(cr_msg, verbose)
      # process data
      dtp <- attempt::attempt(
        ipayipi::dt_process(station_file = station_files[i],
          pipe_house = pipe_house, pipe_seq = pipe_seq, stages = stages,
          output_dt_preffix = output_dt_preffix,
          output_dt_suffix = output_dt_suffix,
          overwrite_pipe_memory = overwrite_pipe_memory,
          verbose = verbose, xtra_v = xtra_v
        )
      )
      invisible(station_files[i])
    })
  cr_msg <- padr(core_message = paste0("  data processed  ", collapes = ""),
    wdth = 80, pad_char = "=", pad_extras = c("|", "", "", "|"),
    force_extras = FALSE, justf = c(0, 0)
  )
  ipayipi::msg(cr_msg, verbose)
  invisible(station_files)
}